# Generated by Django 4.0.4 on 2022-06-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EatenFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ate_food', models.CharField(max_length=100, null=True, verbose_name='food')),
                ('feelings', models.CharField(choices=[('good', 'good'), ('normal', 'normal'), ('can be bad', 'can be bad'), ('bad', 'bad')], max_length=100, null=True, verbose_name='feelings after food')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='eating time')),
                ('meal', models.CharField(choices=[('breakfast', 'breakfast'), ('brunch', 'brunch'), ('first_course', 'first course'), ('main_course', 'main_course'), ('snack', 'snack'), ('evening_meal', 'evening meal')], default=1, max_length=100, verbose_name='meal type')),
                ('feelings', models.CharField(choices=[('good', 'good'), ('normal', 'normal'), ('bad', 'bad')], max_length=100, verbose_name='feelings after food')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='food photo')),
                ('ate food', models.ManyToManyField(to='eaten_food.eatenfood')),
            ],
        ),
    ]
